config/routes.rb
# frozen-string-literal: true

Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :articles
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

# model para articles
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
end

app/models/user.rb
# frozen_string_literal: true

# User model
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 105 },
                    format: { with: URI::MailTo::EMAIL_REGEXP }
  has_secure_password
end

app/controllers/application_controller.rb
# frozen-string-literal: true

# Methods for all controllers
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:danger] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# ArticlesController
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[index show]
  before_action :require_same_user, only: %i[edit update destroy]

  def show; end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(articles_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article was created successfully'
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(articles_params)
      flash[:notice] = 'Article was updated successfully'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def articles_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = 'You can only edit or delete your own articles'
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# a class for categories controller
class CategoriesController < ApplicationController
  def new
  end

  def index
    @categories = Category.all
  end

  def show
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
# frozen-string-literal: true

# create a session controller
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome back, #{user.username}!"
      redirect_to user
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You have logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
# frozen-string-literal: true

# class for Users
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update show destroy]
  before_action :require_user, only: %i[edit update]
  before_action :require_same_user, only: %i[edit update detroy]
  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Your account was updated successfully'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = 'User and all articles created by user have been deleted'
    redirect_to articles_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = 'You can only edit or delete your own account'
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
# frozen-string-literal: true

# Helper for take gravatar image
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded shadow mx-auto d-block')
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_article.html.erb
<section class="container">
  <%@articles.each do |article|%>
    <div class="row justify-content-md-center" id="teste">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            <% if article.user %>
              By <%= link_to article.user.username, user_path(article.user), class: 'text-decoration-none' %>
            <% end %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100)%></p>
            <%= link_to 'View', article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?)%>
              <%= link_to 'Edit', edit_article_path(article.id), class: "btn btn-outline-info" %>
              <%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure you want to delete this article?'}, class: 'btn btn-outline-danger' %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small> Created <%= time_ago_in_words(article.created_at) %> ago,
              edited <%= time_ago_in_words(article.updated_at) %> ago,
            </small>
          </div>
        </div>
      </div>
    </div>
  <%end%>
  <p>
    <%= link_to 'Create new article', new_article_path %>
  </p>
</section>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: 'shadow p-3 mb-3 bg-light rounded' ,local: true) do |f|%>
        <div class=" form-group row mb-3">
          <%= f.label :title, class: 'col-2 col-form-label fst-italic text-secondary' %>
          <div class=" col-10">
            <%= f.text_field :title, class: 'form-control shadow rounded', placeholder: 'Title content' %>
          </div>
        </div>
        <div class=" form-group row mb-3">
          <%= f.label :description, class: 'col-2 col-form-label fst-italic text-secondary' %>
          <div class=" col-10">
            <%= f.text_area :description, rows: 10, class: 'form-control shadow rounded', placeholder: 'Description content' %>
          </div>
        </div>
        <div class="d-flex justify-content-center mb-3">
          <%= f.submit class: "btn btn-outline-success" %>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center">
      <p><%= link_to '[ Cancel and return to articles listing ]', articles_path, class: 'text-info' %></p>
    </div>
  </div>
</div>

app/views/articles/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#" id="logo">Blog Alpha</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: "nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Articles', articles_path, class: "nav-link active" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all articles</h1>
<%= will_paginate @articles, list_classes: %w(pagination justify-content-center), previous_label: 'Previous', next_label: 'Next'%>
<%= render 'article' %>
<%= will_paginate @articles, list_classes: %w(pagination justify-content-center mb-4), previous_label: 'Previous', next_label: 'Next'%>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h2>
<div class="container d-flex justify-content-center">
  <div class="col-8 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
      <div class="card-header font-italic">
        <% if @article.user%>
          By <%= link_to @article.user.username, user_path(@article.user), class: 'text-decoration-none' %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
        <%end%>
      </div>
      <div class="card-body">
        <div class="card-text text-start"><%= simple_format(@article.description) %></div>
        <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
          <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
          <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
        <% end %>
      </div>
      <div class="card-footer text-muted">
        <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
          edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
      </div>
    </div>
  </div>
</div>
</div>

app/views/categories/index.html.erb
<h1>Index</h1>

app/views/categories/new.html.erb
<h1>New</h1>

app/views/categories/show.html.erb
<h1>Show</h1>

app/views/layouts/_footer.html.erb
<footer class="footer py-4 bg-dark text-light" id="sticky-footer">
  <div class="container text-center text-light">
    <span class="text-light">Copyright &copy <%= link_to 'Ronaldo Sena Jr', "https://www.linkedin.com/in/ronaldo-sena-junior", class: "text-light" %></span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to 'Alpha Blog', root_path, class: "navbar-brand", id: "logo"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "View articles", articles_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?"} %>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="d-flex" role="search">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column">
    <%= render 'layouts/navbar' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="p-5 mb-4 bg-light rounded-3 text-center jumbotron text-light">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold">Alpha Blog</h1>
      <p class="lead">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
      <%= link_to 'Sign Up!', signup_path, class: 'btn btn-info btn-lg' %>
      <%= link_to 'Log in!', login_path, class: 'btn btn-success btn-lg' %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Holy guacamole!</strong> You should check in on some of those fields below.
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<%end%>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: 'shadow p-3 mb-3 bg-light rounded', local: true) do |f|%>
        <div class=" form-group row mb-3">
          <%= f.label :username, class: 'col-2 col-form-label fst-italic text-secondary' %>
          <div class=" col-10">
            <%= f.text_field :username, class: 'form-control shadow rounded', placeholder: 'Enter a username' %>
          </div>
        </div>
        <div class=" form-group row mb-3">
          <%= f.label :email, class: 'col-2 col-form-label fst-italic text-secondary' %>
          <div class=" col-10">
            <%= f.email_field :email, class: 'form-control shadow rounded', placeholder: 'Enter your email address' %>
          </div>
        </div>
        <div class=" form-group row mb-3">
          <%= f.label :password, class: 'col-2 col-form-label fst-italic text-secondary' %>
          <div class=" col-10">
            <%= f.password_field :password, class: 'form-control shadow rounded', placeholder: 'Choose your password' %>
          </div>
        </div>
        <div class="d-flex justify-content-center mb-3">
          <%= f.submit(@user.new_record? ? "Sign up": "Update account", class: "btn btn-outline-success") %>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center">
      <p><%= link_to '[ Cancel and return to articles listing ]', articles_path, class: 'text-info' %></p>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>
<%= will_paginate @users, list_classes: %w(pagination justify-content-center), previous_label: 'Previous', next_label: 'Next'%>
<section class="container">
  <%@users.each do |user|%>
    <div class="row justify-content-md-center" id="teste">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            <%= link_to user.username, user, class: 'text-decoration-none' %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text">
              <%= pluralize(user.articles.count, "article")%>
            </p>
            <%= link_to 'View profile', user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <%  if user == current_user %>
                <%= link_to 'Edit profile', edit_user_path(user.id), class: "btn btn-outline-info" %>
              <% end %>
              <% if current_user.admin? %>
                <%= link_to 'Delete User', user_path(user), class: "btn btn-outline-danger", data: { confirm: "Are you sure?", method: :delete} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small> Joined <%= time_ago_in_words(user.created_at) %> ago
            </small>
          </div>
        </div>
      </div>
    </div>
  <%end%>
  <p>
    <%= link_to 'Create new article', new_article_path %>
  </p>
</section>
<%= will_paginate @users, list_classes: %w(pagination justify-content-center mb-4), previous_label: 'Previous', next_label: 'Next'%>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign Up for Alpha Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username%>'s profile</h1>
<%= gravatar_for @user, size: 200%>
<div class="text-center mt-4">
  <%if logged_in? && @user == current_user %>
    <%= link_to 'Edit your profile', edit_user_path(@user), class: "btn btn-outline-info" %>
  <% end %>
</div>
<h3 class="text-center mt-4">Articles</h3>
<%= will_paginate @articles, list_classes: %w(pagination justify-content-center), previous_label: 'Previous', next_label: 'Next'%>
<%= render 'articles/article'%>
<%= will_paginate @articles, list_classes: %w(pagination justify-content-center mb-4), previous_label: 'Previous', next_label: 'Next'%>